# Generated by Django 4.2.5 on 2026-06-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('armor', '0002_armor_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='dynamic_tags',
        ),
        migrations.AddField(
            model_name='armor',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
