services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    environment:
      DEFAULT_USERNAME: ${DEFAULT_USERNAME?DEFAULT_USERNAME environment variable not set}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD?DEFAULT_PASSWORD environment variable not set}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,[::1]}
      SERVICE_ACCOUNT_FILE: ${SERVICE_ACCOUNT_FILE:-}
      SERVICE_ACCOUNT_JSON: ${SERVICE_ACCOUNT_JSON:-}
      SPREADSHEET_ID: ${SPREADSHEET_ID:-}
      SHEET_RANGE: ${SHEET_RANGE:-}
