# Generated by Django 4.2.5 on 2023-10-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('system', models.CharField(max_length=50)),
                ('planet_class', models.CharField(max_length=2)),
                ('moons', models.IntegerField()),
                ('colonized', models.BooleanField()),
                ('terraformed', models.BooleanField()),
                ('contains_flora', models.BooleanField()),
                ('contains_fauna', models.BooleanField()),
                ('contains_sentient_life', models.BooleanField()),
                ('special_traits', models.JSONField()),
                ('points_of_interest', models.JSONField()),
            ],
        ),
    ]
