# Generated by Django 4.2.5 on 2023-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
