# Generated by Django 4.2.5 on 2026-07-21 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SheetImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("dry_run", models.BooleanField(default=True)),
                (
                    "content_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SheetRowBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_fingerprint", models.CharField(max_length=64)),
                (
                    "source_row_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("unresolved", "Unresolved"),
                            ("rejected", "Rejected"),
                            ("stale", "Stale"),
                        ],
                        default="unresolved",
                        max_length=16,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("raw_payload", models.JSONField(default=dict)),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SheetSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spreadsheet_id", models.CharField(max_length=128)),
                ("tab_name", models.CharField(max_length=100)),
                ("range_name", models.CharField(blank=True, max_length=100)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["spreadsheet_id", "tab_name"],
                        name="sheet_impor_spreads_80ba97_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sheetsource",
            constraint=models.UniqueConstraint(
                fields=("spreadsheet_id", "tab_name", "range_name"),
                name="unique_sheet_source_region",
            ),
        ),
        migrations.AddField(
            model_name="sheetrowbinding",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="sheetrowbinding",
            name="last_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="row_bindings",
                to="sheet_imports.sheetimportrun",
            ),
        ),
        migrations.AddField(
            model_name="sheetrowbinding",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="row_bindings",
                to="sheet_imports.sheetsource",
            ),
        ),
        migrations.AddField(
            model_name="sheetimportrun",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="sheet_imports.sheetsource",
            ),
        ),
        migrations.AddIndex(
            model_name="sheetrowbinding",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="sheet_impor_content_a4aefc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sheetrowbinding",
            index=models.Index(
                fields=["source", "status"], name="sheet_impor_source__aceb49_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sheetrowbinding",
            constraint=models.UniqueConstraint(
                fields=("source", "row_fingerprint"),
                name="unique_sheet_source_row_fingerprint",
            ),
        ),
        migrations.AddConstraint(
            model_name="sheetrowbinding",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("content_type__isnull", True), ("object_id__isnull", True)
                    ),
                    models.Q(
                        ("content_type__isnull", False), ("object_id__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="sheet_binding_target_pair",
            ),
        ),
    ]
