# Generated by Django 4.2.5 on 2023-10-11 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weapons', '0001_initial'),
        ('species', '0001_initial'),
        ('factions', '0001_initial'),
        ('armor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletics', models.IntegerField()),
                ('acrobatics', models.IntegerField()),
                ('bluff', models.IntegerField()),
                ('computers', models.IntegerField()),
                ('culture', models.IntegerField()),
                ('disguise', models.IntegerField()),
                ('engineering', models.IntegerField()),
                ('intimidate', models.IntegerField()),
                ('medicine', models.IntegerField()),
                ('perception', models.IntegerField()),
                ('piloting', models.IntegerField()),
                ('sense_motive', models.IntegerField()),
                ('life_science', models.IntegerField()),
                ('physical_science', models.IntegerField()),
                ('slight_of_hand', models.IntegerField()),
                ('survival', models.IntegerField()),
                ('stealth', models.IntegerField()),
                ('diplomacy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('wisdom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='people')),
                ('armors', models.ManyToManyField(blank=True, to='armor.armor')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factions.faction')),
                ('skills', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.skills')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.species')),
                ('stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.stats')),
                ('weapons', models.ManyToManyField(blank=True, to='weapons.weapon')),
            ],
        ),
    ]
