# Generated by Django 4.2.5 on 2023-10-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_faction_alter_person_skills_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skillset',
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Statset',
        ),
    ]
