# Generated by Django 4.2.5 on 2023-10-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_rename_skills_skillset_rename_stats_statset'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='linked_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AddField(
            model_name='statset',
            name='linked_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.skillset'),
        ),
        migrations.AlterField(
            model_name='person',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.statset'),
        ),
    ]
