# Generated by Django 4.2.5 on 2023-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_skillset_linked_person_statset_linked_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
