# Generated by Django 4.2.5 on 2023-10-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_person_location_person_position_person_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='people/images'),
        ),
    ]
