# Generated by Django 4.2.5 on 2024-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='agile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='cybernetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='flier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='genius',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='medical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='mutant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='psychic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='scientist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='stealthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='strong',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='tactician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='tough',
            field=models.BooleanField(default=False),
        ),
    ]
