# Generated by Django 4.2.5 on 2023-10-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_alter_species_image'),
        ('people', '0008_alter_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('level', models.IntegerField()),
                ('alignment', models.CharField(max_length=50)),
                ('deity', models.CharField(max_length=50)),
                ('sf_class', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='people/images')),
                ('inventory', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('features', models.JSONField(blank=True, null=True)),
                ('hero_lab_json', models.JSONField(blank=True, null=True)),
                ('skill_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.skillset')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.species')),
                ('stat_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.statset')),
            ],
        ),
    ]
