# Generated by Django 4.2.5 on 2023-10-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='features',
        ),
        migrations.RemoveField(
            model_name='character',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='character',
            name='level',
        ),
        migrations.RemoveField(
            model_name='character',
            name='location',
        ),
        migrations.RemoveField(
            model_name='character',
            name='sf_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skill_set',
        ),
        migrations.RemoveField(
            model_name='character',
            name='stat_set',
        ),
    ]
