# Generated by Django 4.2.5 on 2024-07-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_person_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='people/images/%(person_name)s')),
                ('linked_person', models.ManyToManyField(blank=True, to='people.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='additional_images',
            field=models.ManyToManyField(blank=True, to='people.personimage'),
        ),
    ]
