# Generated by Django 4.2.5 on 2024-07-21 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_rename_image_personimage_additional_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='personimage',
            name='linked_person',
        ),
        migrations.AddField(
            model_name='personimage',
            name='linked_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
    ]
