# Generated by Django 4.2.5 on 2025-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_personimage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='people/images/'),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='additional_image',
            field=models.ImageField(blank=True, upload_to='people/images/additional_images/'),
        ),
    ]
