# Generated by Django 4.2.5 on 2025-09-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0014_alter_person_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="person",
            name="agile",
        ),
        migrations.RemoveField(
            model_name="person",
            name="cybernetic",
        ),
        migrations.RemoveField(
            model_name="person",
            name="engineer",
        ),
        migrations.RemoveField(
            model_name="person",
            name="flier",
        ),
        migrations.RemoveField(
            model_name="person",
            name="genius",
        ),
        migrations.RemoveField(
            model_name="person",
            name="leader",
        ),
        migrations.RemoveField(
            model_name="person",
            name="medical",
        ),
        migrations.RemoveField(
            model_name="person",
            name="mutant",
        ),
        migrations.RemoveField(
            model_name="person",
            name="psychic",
        ),
        migrations.RemoveField(
            model_name="person",
            name="scientist",
        ),
        migrations.RemoveField(
            model_name="person",
            name="stealthy",
        ),
        migrations.RemoveField(
            model_name="person",
            name="strong",
        ),
        migrations.RemoveField(
            model_name="person",
            name="tactician",
        ),
        migrations.RemoveField(
            model_name="person",
            name="tough",
        ),
        migrations.AddField(
            model_name="person",
            name="traits",
            field=models.ManyToManyField(blank=True, to="people.trait"),
        ),
    ]
