# Generated by Django 4.2.5 on 2026-05-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_trait_remove_person_agile_remove_person_cybernetic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_source_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
