# Generated by Django 4.2.5 on 2026-06-28 02:18

from django.db import migrations, models


def copy_people_tags_to_shared(apps, schema_editor):
    Person = apps.get_model('people', 'Person')
    LegacyTag = apps.get_model('people', 'Tag')
    SharedTag = apps.get_model('tags', 'Tag')

    legacy_tags_by_id = {}
    for legacy_tag in LegacyTag.objects.all():
        shared_tag, _ = SharedTag.objects.get_or_create(name=legacy_tag.name)
        legacy_tags_by_id[legacy_tag.id] = shared_tag.id

    old_through = Person.tags.through
    new_through = Person.shared_tags.through
    for relation in old_through.objects.all().iterator():
        shared_tag_id = legacy_tags_by_id.get(relation.tag_id)
        if shared_tag_id is None:
            continue
        new_through.objects.get_or_create(person_id=relation.person_id, tag_id=shared_tag_id)


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('people', '0017_tag_person_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shared_tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
        migrations.RunPython(copy_people_tags_to_shared, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='person',
            name='tags',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='shared_tags',
            new_name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
