# Generated by Django 4.2.5 on 2026-07-21 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0018_delete_tag_alter_person_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "normalized_name",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("normalized_name", models.CharField(editable=False, max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ship", "Ship"),
                            ("branch", "Branch"),
                            ("department", "Department"),
                            ("team", "Team"),
                            ("clan", "Clan"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="people.organizationunit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="age_text",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="person",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PersonRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unresolved_name", models.CharField(blank=True, max_length=100)),
                ("relationship_type", models.CharField(db_index=True, max_length=50)),
                (
                    "family_name",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "from_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="people.person",
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="people.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonProfileFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("value", models.TextField(blank=True)),
                (
                    "normalized_value",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_facts",
                        to="people.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_marker", models.CharField(blank=True, max_length=20)),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="people.capability",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="people.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100)),
                ("rank", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(blank=True, db_index=True, max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="people.person",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="people.organizationunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=100),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("alias", "Alias"),
                            ("hero", "Hero identity"),
                            ("nickname", "Nickname"),
                            ("former", "Former name"),
                        ],
                        default="alias",
                        max_length=16,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="people.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccommodationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=50)),
                ("section", models.CharField(blank=True, db_index=True, max_length=50)),
                ("direction", models.CharField(blank=True, max_length=50)),
                ("room_type", models.CharField(blank=True, max_length=50)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodations",
                        to="people.person",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="personrelationship",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("to_person__isnull", False), ("unresolved_name", "")),
                    models.Q(
                        ("to_person__isnull", True),
                        models.Q(("unresolved_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="relationship_resolved_or_named",
            ),
        ),
        migrations.AddIndex(
            model_name="personprofilefact",
            index=models.Index(
                fields=["key", "normalized_value"], name="people_pers_key_86b4ee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personprofilefact",
            constraint=models.UniqueConstraint(
                fields=("person", "key"), name="unique_person_profile_fact"
            ),
        ),
        migrations.AddConstraint(
            model_name="personcapability",
            constraint=models.UniqueConstraint(
                fields=("person", "capability"), name="unique_person_capability"
            ),
        ),
        migrations.AddIndex(
            model_name="personassignment",
            index=models.Index(
                fields=["unit", "rank", "role"], name="people_pers_unit_id_6851ad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personassignment",
            constraint=models.UniqueConstraint(
                fields=("person", "unit", "role"), name="unique_person_unit_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="personalias",
            constraint=models.UniqueConstraint(
                fields=("person", "normalized_name", "kind"), name="unique_person_alias"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationunit",
            index=models.Index(
                fields=["kind", "normalized_name"], name="people_orga_kind_8976a3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationunit",
            constraint=models.UniqueConstraint(
                fields=("normalized_name", "kind"), name="unique_organization_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="accommodationassignment",
            constraint=models.UniqueConstraint(
                fields=("person", "room", "section", "direction"),
                name="unique_person_accommodation",
            ),
        ),
    ]
