# Generated by Django 4.2.5 on 2026-07-21 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0019_capability_organizationunit_person_age_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPersonView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("shared", "Shared")],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("filters", models.JSONField(default=dict)),
                ("columns", models.JSONField(blank=True, default=list)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_person_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="savedpersonview",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_saved_person_view_name"
            ),
        ),
    ]
