# Generated by Django 4.2.5 on 2023-10-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home_world', models.CharField(max_length=100)),
                ('society', models.CharField(choices=[('monarchy', 'Monarchy'), ('theocracy', 'Theocracy'), ('democracy', 'Democracy'), ('caste', 'Caste'), ('tribal', 'Tribal'), ('free', 'Free'), ('unknown', 'Unknown'), ('empire', 'Empire'), ('conglomerate', 'Conglomerate'), ('aristocracy', 'Aristocracy'), ('multiple', 'Multiple'), ('anarchy', 'Anarchy'), ('technocracy', 'Technocracy')], max_length=50)),
                ('accord_status', models.CharField(choices=[('ally', 'Ally'), ('member', 'Member'), ('peace', 'Peace Treaty'), ('enemy', 'Enemy'), ('nuetral', 'Nuetral'), ('unknown', 'Unknown'), ('undiscovered', 'Undiscovered')], max_length=20)),
                ('background', models.TextField()),
                ('sociology', models.TextField(max_length=20)),
                ('physiology', models.TextField(max_length=20)),
                ('racial_traits', models.JSONField()),
                ('size', models.CharField(choices=[('diminutive', 'Diminutive'), ('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('huge', 'Huge'), ('gargantuan', 'Gargantuan'), ('colossal', 'Colossal'), ('planetary', 'Planetary')], max_length=20)),
                ('type', models.CharField(choices=[('animal', 'Animal'), ('biotech', 'Bio-Tech'), ('plant', 'Plant'), ('metamorph', 'Metamorph'), ('unique', 'Unique')], max_length=50)),
                ('air', models.CharField(choices=[('oxygen', 'Oxygen'), ('nitrogen', 'Nitrogen'), ('carbon-dioxide', 'Carbon Dioxide'), ('argon', 'Argon'), ('unique', 'Unique'), ('xenon', 'Xenon'), ('dihydrogen-oxide', 'Dihydrogen Oxide'), ('hydrogen', 'Hydrogen'), ('helium', 'Helium'), ('neon', 'Neon')], max_length=50)),
                ('reproduction_method', models.CharField(choices=[('standard', 'Standard'), ('asexual', 'Asexual'), ('fission', 'Fission'), ('clone', 'Clone'), ('unique', 'Unique')], max_length=20)),
                ('hours_of_sleep', models.IntegerField()),
                ('days_without_food', models.IntegerField()),
                ('days_without_water', models.IntegerField()),
                ('strength_rating', models.IntegerField()),
                ('toughness_rating', models.IntegerField()),
                ('speed_rating', models.IntegerField()),
                ('intelligence_rating', models.IntegerField()),
                ('natural_weapons', models.BooleanField()),
                ('natural_armor', models.BooleanField()),
                ('can_fly', models.BooleanField()),
                ('aquatic', models.BooleanField()),
                ('amphibious', models.BooleanField()),
                ('telepathic', models.BooleanField()),
                ('psionic', models.BooleanField()),
                ('gravity', models.CharField(choices=[('light', 'Light'), ('standard', 'Standard'), ('heavy', 'Heavy')], max_length=15)),
                ('special_abilities', models.JSONField()),
                ('locomotion_method', models.CharField(choices=[('bipedal', 'Bipedal'), ('tentacle', 'Tentacle'), ('multiped', 'Multiped'), ('flight', 'Flight'), ('serpentine', 'Serpentine'), ('metamorph', 'Metamorph'), ('float', 'Float'), ('quadruped', 'Quadruped'), ('octoped', 'Octoped')], max_length=20)),
            ],
        ),
    ]
