# Generated by Django 4.2.5 on 2023-10-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='physiology',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='sociology',
            field=models.TextField(),
        ),
    ]
