# Generated by Django 4.2.5 on 2023-10-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_alter_species_physiology_alter_species_sociology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='accord_status',
            field=models.CharField(choices=[('founder', 'Founding Member'), ('ally', 'Ally'), ('member', 'Member'), ('peace', 'Peace Treaty'), ('enemy', 'Enemy'), ('nuetral', 'Nuetral'), ('unknown', 'Unknown'), ('undiscovered', 'Undiscovered')], max_length=20),
        ),
    ]
