# Generated by Django 4.2.5 on 2023-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_alter_species_accord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
