# Generated by Django 4.2.5 on 2023-10-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_species_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='image',
            field=models.ImageField(blank=True, upload_to='species'),
        ),
    ]
