# Generated by Django 4.2.5 on 2023-10-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_species_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='species/images/'),
        ),
    ]
