# Generated by Django 4.2.5 on 2025-09-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_alter_species_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='accord_status',
            field=models.CharField(blank=True, choices=[('founder', 'Founding Member'), ('ally', 'Ally'), ('member', 'Member'), ('peace', 'Peace Treaty'), ('enemy', 'Enemy'), ('nuetral', 'Nuetral'), ('unknown', 'Unknown'), ('undiscovered', 'Undiscovered')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='air',
            field=models.CharField(blank=True, choices=[('oxygen', 'Oxygen'), ('nitrogen', 'Nitrogen'), ('carbon-dioxide', 'Carbon Dioxide'), ('argon', 'Argon'), ('unique', 'Unique'), ('xenon', 'Xenon'), ('dihydrogen-oxide', 'Dihydrogen Oxide'), ('hydrogen', 'Hydrogen'), ('helium', 'Helium'), ('neon', 'Neon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='amphibious',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='aquatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='can_fly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='days_without_food',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='days_without_water',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='gravity',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('standard', 'Standard'), ('heavy', 'Heavy')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='home_world',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='hours_of_sleep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='intelligence_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='locomotion_method',
            field=models.CharField(blank=True, choices=[('bipedal', 'Bipedal'), ('tentacle', 'Tentacle'), ('multiped', 'Multiped'), ('flight', 'Flight'), ('serpentine', 'Serpentine'), ('metamorph', 'Metamorph'), ('float', 'Float'), ('quadruped', 'Quadruped'), ('octoped', 'Octoped')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='natural_armor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='natural_weapons',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='physiology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='psionic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='racial_traits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='reproduction_method',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('asexual', 'Asexual'), ('fission', 'Fission'), ('clone', 'Clone'), ('unique', 'Unique')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='size',
            field=models.CharField(blank=True, choices=[('diminutive', 'Diminutive'), ('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('huge', 'Huge'), ('gargantuan', 'Gargantuan'), ('colossal', 'Colossal'), ('planetary', 'Planetary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='society',
            field=models.CharField(blank=True, choices=[('monarchy', 'Monarchy'), ('theocracy', 'Theocracy'), ('democracy', 'Democracy'), ('caste', 'Caste'), ('tribal', 'Tribal'), ('free', 'Free'), ('unknown', 'Unknown'), ('empire', 'Empire'), ('conglomerate', 'Conglomerate'), ('aristocracy', 'Aristocracy'), ('multiple', 'Multiple'), ('anarchy', 'Anarchy'), ('technocracy', 'Technocracy')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='sociology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='special_abilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='speed_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='strength_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='telepathic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='toughness_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='type',
            field=models.CharField(blank=True, choices=[('animal', 'Animal'), ('biotech', 'Bio-Tech'), ('plant', 'Plant'), ('metamorph', 'Metamorph'), ('unique', 'Unique')], max_length=50, null=True),
        ),
    ]
