# Generated by Django 4.2.5 on 2026-05-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_species_schema_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='match_status',
        ),
    ]
