# Generated by Django 4.2.5 on 2026-05-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_remove_species_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='image_source_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
