# Generated by Django 4.2.5 on 2023-10-11 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weapon_type', models.CharField(max_length=50)),
                ('damage', models.CharField(max_length=20)),
                ('critical', models.CharField(max_length=20)),
                ('range_increment', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('usage', models.CharField(max_length=50)),
                ('special_properties', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('secondary_weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weapons.weapon')),
            ],
        ),
    ]
