# Generated by Django 4.2.5 on 2023-10-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='events')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('battle', 'Battle'), ('historical', 'Historical'), ('discovery', 'Discovery'), ('event', 'Event'), ('disaster', 'Disaster'), ('meeting', 'Meeting'), ('other', 'Other'), ('in_game_event', 'In-Game Event'), ('notable', 'Notable')], max_length=50)),
            ],
        ),
    ]
