# Generated by Django 4.2.5 on 2023-10-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('species', '0001_initial'),
        ('events', '0001_initial'),
        ('factions', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='factions',
            field=models.ManyToManyField(blank=True, to='factions.faction'),
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(blank=True, to='people.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='species',
            field=models.ManyToManyField(blank=True, to='species.species'),
        ),
        migrations.AddField(
            model_name='event',
            name='worlds',
            field=models.ManyToManyField(blank=True, to='worlds.world'),
        ),
    ]
