# Generated by Django 4.2.5 on 2026-06-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('events', '0003_event_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
