# Generated by Django 4.2.5 on 2025-09-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('leader', models.CharField(blank=True, max_length=100, null=True)),
                ('faction', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
