# Generated by Django 4.2.5 on 2025-09-06 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time this party was created.', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time this party was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='party',
            name='faction',
            field=models.CharField(blank=True, help_text='Faction this party is associated with.', max_length=100, null=True, verbose_name='Faction'),
        ),
        migrations.AlterField(
            model_name='party',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Should this party be hidden from public view?', verbose_name='Hidden'),
        ),
        migrations.AlterField(
            model_name='party',
            name='leader',
            field=models.CharField(blank=True, help_text='Name of the party leader.', max_length=100, null=True, verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='party',
            name='location',
            field=models.CharField(blank=True, help_text='Current location of the party.', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(help_text='Enter the name of the party.', max_length=100, verbose_name='Party Name'),
        ),
        migrations.AlterField(
            model_name='party',
            name='purpose',
            field=models.TextField(blank=True, help_text='Describe the purpose or mission of the party.', null=True, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(blank=True, help_text='Type or category of the party (e.g., adventuring, political, etc.).', max_length=100, null=True, verbose_name='Party Type'),
        ),
    ]
