# Generated by Django 4.2.5 on 2025-09-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_alter_person_image_and_more'),
        ('party', '0002_party_created_at_party_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(help_text='Select members of the party.', related_name='parties', to='people.person', verbose_name='Members'),
        ),
    ]
